DROP TABLE IF EXISTS base_model;
	 
	CREATE TABLE base_model (
	  id INT AUTO_INCREMENT  PRIMARY KEY,
	  created_at TIMESTAMP NOT NULL,
	  updated_at TIMESTAMP NOT NULL
	);
	 
	INSERT INTO base_model (created_at, updated_at) VALUES
	  (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
	  (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
	  (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());